image: openjdk:8-jdk

before_script:
  - cd /opt
  - wget http://ftp.unicamp.br/pub/apache/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
  - tar xzvf apache-maven-3.6.2-bin.tar.gz
  - export PATH=${PATH}:/opt/apache-maven-3.6.2/bin/
  - cd $CI_PROJECT_DIR

cache:
  key: BUILD
  paths:
    - target/*.jar

stages:
  - test
  - build
  - deploy
  
teste:
  stage: test
  script:
    - mvn test
  
build:
  stage: build
  script:
    - mvn clean package
  artifacts:
    name: Pacote-Build
    paths:
      - target/*.jar
    expire_in: 1 week
  cache:
    key: BUILD
    paths:
      - target/*.jar
    policy: push

deploy_heroku:
  stage: deploy
  before_script:
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    - heroku plugins:install java
    - heroku deploy:jar target/agenda-pets-0.0.1-SNAPSHOT.jar --app dn-teste
  cache:
    key: BUILD
    paths:
      - target/*.jar
    policy: pull
  environment:
    name: HerokuTest
    url: https://dn-teste.herokuapp.com/playground
  when: manual